language: elixir
elixir: '1.6'

script:
  # This is basically `mix test` with coverage enabled.
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - elixir: '1.6'
      otp_release: '20.2'

    - elixir: '1.6'
      otp_release: '20.2'
      env:
        - RUN_DIALYZER=1
      cache:
        directories:
          - $HOME/.mix
          - $HOME/.pltcache

      before_script:
        - mix compile
        # Juggle cached PLTs.
        - mkdir -p ~/.pltcache
        - cp ~/.pltcache/*-dev.plt _build/dev/ || true
        - mix dialyzer --plt
        - cp _build/dev/*-dev.plt ~/.pltcache/
        # Now that we've done the PLT dance, we can run dialyzer.

      script:
        - mix dialyzer --halt-exit-status

    - group: trusty_latest
      jdk: openjdk8
      env:
        - BAZEL_VERSION=0.11.0
        - PROTOC_VERSION=3.5.1
        - PROTOBUF_ELIXIR_VERSION=0.5.2

      install:
        # Install Bazel
        - curl -L "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-without-jdk-installer-linux-x86_64.sh" > bazel-installer.sh
        - bash bazel-installer.sh --user
        # Install protoc
        - curl -L https://github.com/google/protobuf/releases/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip > protoc.zip
        - mkdir ~/protoc && unzip -d ~/protoc protoc.zip && ln -s ~/protoc/bin/protoc ~/bin/protoc
        # Install protoc-gen-elixir
        - mix local.hex --force && mix escript.install --force hex protobuf "$PROTOBUF_ELIXIR_VERSION"
        # Check everything is available
        - export PATH="$HOME/.mix/escripts:$PATH"
        - echo "Installed Bazel ($(which bazel)), protoc ($(which protoc)), protobuf-elixir ($(which protoc-gen-elixir))"
      script:
        - ./generate_protos.sh
        - '[[ -z "$(git status -s lib/)" ]]'
